### ISSUE TITLE
"Error reading power management state for sensor udisks2"

### ISSUE THREAD

**Issue by n1vux** [alexmurray/indicator-sensors#13]
We've just started getting popups saying "Error reading power management state for sensor udisks2" on one of our Ubuntu/ThinkPad laptops.

Does that mean our kernel has updated to be incompatible with indicator-sensors and udisks2, or that our disk is failing ? 

(The only hits that Google found for the message string was the source code and POT translations.)

**Comment by n1vux** [comment]
oh, maybe never mind ?  I got a screen cap of pop-up on the laptop.
second half of message is likely the real problem, just being reported by indicator-sensors re udisk2/.

> ST9160314AS_5VCHENVPGDBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached

I see several other DBus subscribers get this message when NM or oter subsystems flood DBUS.

**Comment by alexmurray** [comment]
Ok - will close this then but let me know if you have any other issues.

**Comment by n1vux** [comment]
Roger wilco,

thank you for this module ... i rely on indicator-sensors and related panel
items because i don't trust the power mgt totally, i've had one or two
thermal run-aways and want to nip trouble in the bud.
​

**Comment by alexmurray** [comment]
No worries - you're welcome - glad you find it useful.
