### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by quequotion** [alexmurray/indicator-sensors#15]
Lately I get dozens and dozens of DEBUG and MESSAGE from indicator-sensors; to the point that it is becoming difficult to read the system log without having to scroll through a few pages of indicator-sensors' messages. This needs to be configurable, either by dconf, command-line,  or by matching the level set for the kernel.

**Comment by alexmurray** [comment]
Reduced log level to warning messages only by default, and added command-line option --verbose / -v to get full set of messages again in https://github.com/alexmurray/indicator-sensors/commit/a5ee33305d4ab21196396e4e85333fdfbd789590
