### ISSUE TITLE
indicator-sensors writes to disk rather frequently

### ISSUE THREAD

**Issue by quequotion** [alexmurray/indicator-sensors#16]
I checked iotop because I was having a hard time getting my disks to timeout and spin down.

strace indicator-sensors shows it renaming files in its config directory every few seconds:

rename("/home/$USER/.config/indicator-sensors/sensors.YD36XY", "/home/$USER/.config/indicator-sensors/sensors") = 0

**Comment by alexmurray** [comment]
Should hopefully be reduced after https://github.com/alexmurray/indicator-sensors/commit/6bfed1755c2093fac826764f75af3ed021973ba2 - can you please test if possible?

**Comment by quequotion** [comment]
Much better! I only noticed it happening a few times just after start  up.
