### ISSUE TITLE
detecting fans

### ISSUE THREAD

**Issue by chrismatchett** [alexmurray/indicator-sensors#24]
Hi,

Your utility is working well on my HP Prodesk 400 G4 Ubuntu 18.04 desktop and showing cpu temp, free memory and ssd temp.

There are no fans showing. I'm guessing this is my desktop's problem and not your software. How do I confirm if my fan is / is not available to the sensors?

Many thanks,

Chris

**Comment by alexmurray** [comment]
Can you post the output after running the `sensors` command in a terminal? Also indicator-sensors doesn't show memory usage - only sensor readings - are you sure you are using indicator-sensors?

**Comment by iamkk11** [comment]
kevin@kevin:~$ indicator-sensors
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[aticonfig] WARNING: Error calling aticonfig to detect if running on a hybrid system with integrated GPU active: Failed to execute child process “aticonfig” (No such file or directory)

**Comment by alexmurray** [comment]
This error is not relevant - as asked above, if you are experiencing this issue can you please run `sensors` and post this output?

**Comment by iamkk11** [comment]
> This error is not relevant - as asked above, if you are experiencing this issue can you please run `sensors` and post this output?

kevin@kevin:~$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +43.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +41.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +42.0°C  (high = +100.0°C, crit = +100.0°C)

**Comment by iamkk11** [comment]
Ive never seen fan in my indicator sensor. See output above. Only temperature. I am running HP Spectre notepad.

**Comment by alexmurray** [comment]
Ok so indicator-sensors can only see the same set of sensors as the `sensors` command - since in this case it also cannot see the fan then indicator-sensors cannot either. Closing this issue.
