### ISSUE TITLE
No Sensors Enabled for Monitoring

### ISSUE THREAD

**Issue by brandiqa** [alexmurray/indicator-sensors#25]
Am running Elementary OS Juno and when I try to run indicator-sensors, I get a pop up that says
"No Sensors Enabled for Monitoring".

The message says open "Preferences Window" but there's nothing to click. No icon appears and there is no such option in the start menu.

**Comment by alexmurray** [comment]
indicator-sensors uses libappindicator for display - does the Elementary desktop environment support appindicators?

**Comment by wizath** [comment]
https://www.linuxuprising.com/2018/08/how-to-re-enable-ayatana-appindicators.html

**Comment by brandiqa** [comment]
@alexmurray On my list of installed packages, `libappindicator1` and `libappindicator3-1` have been installed. Following the instructions on the link provided by @wizath worked great for me. Also discovered it fixed a similar problem with another program, stacer.
