### ISSUE TITLE
How do I change the temperature level icons on my status bar?

### ISSUE THREAD

**Issue by iamkk11** [alexmurray/indicator-sensors#29]

**Comment by pszi1ard** [comment]
I'm also interested in this mainly because in my case the icon seems to be missing: 
![image](https://user-images.githubusercontent.com/1333767/76788197-bd8e0280-67ba-11ea-8129-10918311b8fd.png)

**Comment by iamkk11** [comment]
> I'm also interested in this mainly because in my case the icon seems to be missing:
> ![image](https://user-images.githubusercontent.com/1333767/76788197-bd8e0280-67ba-11ea-8129-10918311b8fd.png)

I was able to do it by basically rebuilding the snap. I replaced the icon images with my own icons.

**Comment by iamkk11** [comment]
Rebuild the snap with your own custom images.

**Comment by pszi1ard** [comment]
> Rebuild the snap with your own custom images.

OK, so the snap is broken. Who's in charge of the snap so I can file a report int he right place?

**Comment by iamkk11** [comment]
> > Rebuild the snap with your own custom images.
> 
> OK, so the snap is broken. Who's in charge of the snap so I can file a report int he right place? Looks like this is the right place, so I guess I will file a new issue?

Use my fork:

https://github.com/iamkk11/sensors
