### ISSUE TITLE
No data except CPU temp on Ubuntu 20.04

### ISSUE THREAD

**Issue by kreuzerkrieg** [alexmurray/indicator-sensors#32]
For some reason I dont get any reading except CPU temp
![image](https://user-images.githubusercontent.com/829317/87244887-5f5fec00-c449-11ea-89d5-3342350029e3.png)
I would like see the fan speed and ssd temp

Installed via snap

**Comment by alexmurray** [comment]
indicator-sensors relies on the Linux kernel to provide support for underlying sensors - as such it reports the same readings as the `sensors` command does on the command-line (plus some extras) - so I suggest filing a bug report upstream to get your particular hardware supported directly by the kernel. For SSDs we use udisks2 to provide the readings - and most SSDs do not support the SMART disk attributes which provide temperature readings. So from what I can tell there is no bug or issue in indicator-sensors itself.

**Comment by kreuzerkrieg** [comment]
This is what I thought, thanks for clarifying.
