### ISSUE TITLE
GUI labeling meaning needs explanation. One temp sensor reading is very high while some fans reading are none.

### ISSUE THREAD

**Issue by sunbearc22** [alexmurray/indicator-sensors#37]
Can you help me understand the meaning of `virtual` and `libsensors` in the Sensor category? 

Below shows a picture of the readings reported by this app.  My questions are:

- Why are there two `Sensor 2` result. Do they mean the same thing? 
- Also Sensor 2 is reporting 92 deg C. Is it possible? 
- Finally, fans 2, 3, 4 has zero rpm. Why is this the case? The mb has CPU_FAN, CPU_OPT, HS_FAN, CHA_FAN1, CHA_FAN2 and M.2_FAN, where CPU_OPT, HS_FAN are unused. How do I related the fan numbering by this app to the labeling on the mb?

   
![indicator-sensors appearance and readings](https://user-images.githubusercontent.com/23432142/128230536-5c2f02d3-4b8b-48e9-8da9-d2b398d99539.png)

**Comment by alexmurray** [comment]
These labels come from the kernel driver themselves or libsensors - you should see the same labels if you run the `sensors` command in a terminal - if you feel these are incorrect then this is either an issue that needs fixing in the kernel driver or libsensors.

**Comment by alexmurray** [comment]
Oh sorry I missed the bit about virtual - these are 'virtual' sensors which are designed to show either the sensor with the highest value (`max`) or the one that changes the most often (`dynamic`) - this can be used if you want to just see the highest temperature or most dynamic one shown in the task bar without having to actually figure out what that may be yourself manually.
