### ISSUE TITLE
Missing nvme-pci-0100 sensor

### ISSUE THREAD

**Issue by dtrunk90** [alexmurray/indicator-sensors#38]
System: Ubuntu Budgie 20.04.3 LTS
SSD model: Samsung SSD 980 PRO 2TB

The indicator is missing a sensor:
![Bildschirmfoto vom 2022-01-25 15-18-13](https://user-images.githubusercontent.com/636557/150993879-d846426f-7ee5-407d-950b-186ab201b766.png)

```
$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +33.0°C  (high = +76.0°C, crit = +86.0°C)
Core 0:        +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 1:        +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 2:        +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 3:        +30.0°C  (high = +76.0°C, crit = +86.0°C)
Core 4:        +32.0°C  (high = +76.0°C, crit = +86.0°C)
Core 8:        +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 9:        +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 10:       +30.0°C  (high = +76.0°C, crit = +86.0°C)
Core 11:       +32.0°C  (high = +76.0°C, crit = +86.0°C)
Core 16:       +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 17:       +32.0°C  (high = +76.0°C, crit = +86.0°C)
Core 18:       +32.0°C  (high = +76.0°C, crit = +86.0°C)
Core 19:       +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 20:       +32.0°C  (high = +76.0°C, crit = +86.0°C)
Core 24:       +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 25:       +31.0°C  (high = +76.0°C, crit = +86.0°C)
Core 26:       +33.0°C  (high = +76.0°C, crit = +86.0°C)
Core 27:       +31.0°C  (high = +76.0°C, crit = +86.0°C)

radeon-pci-6500
Adapter: PCI adapter
temp1:        +66.0°C  (crit = +120.0°C, hyst = +90.0°C)

nvme-pci-0100
Adapter: PCI adapter
Composite:    +46.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +46.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +51.9°C  (low  = -273.1°C, high = +65261.8°C)
```

I've moved from a 1TB WD SSD to a 2TB Samsung SSD recently and copied the whole SSD to the new one. Maybe this has side effects? But `sensors` output looks good to me.

**Comment by alexmurray** [comment]
Thanks for the bug report - can you please provide some more details - what version of indicator-sensors are you using? What distro are you running it on? Thanks.

**Comment by dtrunk90** [comment]
Sorry, forgot to mention the version I'm running:
```
$ LANG=en snap list indicator-sensors
Name               Version  Rev  Tracking       Publisher   Notes
indicator-sensors  1.2      291  latest/stable  alexmurray  -
```

OS + Version is provided in my first comment.

**Comment by alexmurray** [comment]
Hmm I wonder if perhaps this is due to the version of libsensors used by the `indicator-sensors` snap (this comes from Ubuntu 20.04) - so I suppose we could either build this from source ourselves as a separate `part` or wait for Ubuntu 22.04 and upgrade the snap to `base: core22` and get it for free then...

**Comment by dtrunk90** [comment]
Not sure. It worked before I exchanged my WD 1TB SSD with my new Samsung SSD.
```
$ LANG=en apt-cache policy lm-sensors
lm-sensors:
  Installed: 1:3.6.0-2ubuntu1
  Candidate: 1:3.6.0-2ubuntu1
  Version table:
 *** 1:3.6.0-2ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by alexmurray** [comment]
indicator-sensors was recently updated to use `core22` and so uses a newer version of `libsensors5` - can you please check the latest stable snap version and see if this resolves this issue? Thanks.

**Comment by dtrunk90** [comment]
Unfortunately i switched to a budgie applet already to get rid of snap.

**Comment by alexmurray** [comment]
Ok no worries - will close this issue then.
