### ISSUE TITLE
ryzen 9 7940hs ubuntu 22.04 core sensors none?

### ISSUE THREAD

**Issue by Dezinger** [alexmurray/indicator-sensors#47]
ryzen 9 7940hs ubuntu 22.04 core sensors none?
![image](https://github.com/alexmurray/indicator-sensors/assets/432272/c15dca25-db2e-469f-8497-6e78c9fa5952)

**Comment by alexmurray** [comment]
What kernel version are you using?

**Comment by Dezinger** [comment]
6.5.0-21-generic

**Comment by alexmurray** [comment]
Can you try running:

    sudo sensors-detect

**Comment by Dezinger** [comment]
Sorry, no sensors were detected.
[sensors-detect.log](https://github.com/alexmurray/indicator-sensors/files/14390176/sensors-detect.log)

**Comment by alexmurray** [comment]
Ok. So indicator-sensors relies on the underlying libsensors library to get sensor readings - and so if sensors-detect can't find any then there is nothing we can do. Sorry.
