### ISSUE TITLE
Panel icon refuses to show temperature of any sensor - Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by herb2k** [alexmurray/indicator-sensors#48]
Since an update to Ubuntu 24.04 LTS, the panel refuses to show the temperature of any sensor. It either shows ... or the icon only.

Output from launching in verbose mode:

Gtk-Message: 23:52:17.602: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
[indicator] DEBUG: new primary sensor path libsensors/coretemp-isa-0000/0 (previously (null))
[indicator] DEBUG: Setting primary sensor path to: libsensors/coretemp-isa-0000/0
[libsensors] DEBUG: Trying to initialise libsensors with default path...

[udisks2] DEBUG: Trying to get udisks client
[nvidia] DEBUG: searching for sensors
[max] DEBUG: creating virtual sensor
[store] DEBUG: inserted sensor virtual/max with label Δ
[max] DEBUG: attaching to signals
[libsensors] DEBUG: searching for sensors
[store] DEBUG: inserted sensor libsensors/coretemp-isa-0000/0 with label Package id 0
[indicator] DEBUG: Creating menu item for newly enabled sensor libsensors/coretemp-isa-0000/0
[indicator] DEBUG: Using sensor with path libsensors/coretemp-isa-0000/0 as primary
[indicator] DEBUG: Checking new primary sensor item
[max] DEBUG: sensor enabled: Package id 0
[max] MESSAGE: New highest value sensor: Package id 0 (value 61.000000)
[store] DEBUG: inserted sensor libsensors/coretemp-isa-0000/4 with label Core 0
[store] DEBUG: inserted sensor libsensors/coretemp-isa-0000/8 with label Core 1
[store] DEBUG: inserted sensor libsensors/BAT0-acpi-0/0 with label in0
[indicator] DEBUG: Creating menu item for newly enabled sensor libsensors/BAT0-acpi-0/0
[libsensors] DEBUG: Ignoring unimplemented sensor type 5
[libsensors] WARNING: could not get input subfeature for sensor 'BAT0-acpi-0'
[store] DEBUG: inserted sensor libsensors/acpitz-acpi-0/0 with label temp1
[store] DEBUG: inserted sensor libsensors/acpitz-acpi-0/1 with label temp2
[store] DEBUG: inserted sensor libsensors/acpitz-acpi-0/2 with label temp3
[store] DEBUG: inserted sensor libsensors/acpitz-acpi-0/3 with label temp4
[store] DEBUG: inserted sensor libsensors/acpitz-acpi-0/4 with label temp5
[indicator] DEBUG: Creating menu item for newly enabled sensor libsensors/acpitz-acpi-0/4
[max] DEBUG: sensor enabled: temp5
[store] DEBUG: inserted sensor libsensors/acpitz-acpi-0/5 with label temp6
[dynamic] DEBUG: creating virtual sensor
[store] DEBUG: inserted sensor virtual/dynamic with label Δ
[dynamic] DEBUG: attaching to signals
[dynamic] DEBUG: sensor enabled: Package id 0
[dynamic] DEBUG: Creating new dynamic rate data for sensor: Package id 0
[dynamic] DEBUG: sensor enabled: temp5
[dynamic] DEBUG: Creating new dynamic rate data for sensor: temp5
[aticonfig] DEBUG: Checking for hybrid system with integrated GPU active
[aticonfig] WARNING: Error calling aticonfig to detect if running on a hybrid system with integrated GPU active: Failed to execute child process “aticonfig” (No such file or directory)
[udisks2] DEBUG: Error getting udisks2 client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.244" (uid=1000 pid=33787 comm="/snap/indicator-sensors/314/usr/bin/indicator-sens" label="snap.indicator-sensors.indicator-sensors (enforce)") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination=":1.6" (uid=0 pid=1634 comm="/usr/libexec/udisks2/udisksd" label="unconfined")
[dbus-plugin] DEBUG: Acquired a message bus connection

[dbus-plugin] DEBUG: Creating an ActiveSensor at path /com/github/alexmurray/IndicatorSensors/ActiveSensors/libsensors/coretemp_isa_0000/0

[dbus-plugin] DEBUG: Creating an ActiveSensor at path /com/github/alexmurray/IndicatorSensors/ActiveSensors/libsensors/BAT0_acpi_0/0

[dbus-plugin] DEBUG: Creating an ActiveSensor at path /com/github/alexmurray/IndicatorSensors/ActiveSensors/libsensors/acpitz_acpi_0/4

[dbus-plugin] DEBUG: Acquired the name com.github.alexmurray.IndicatorSensors

[dynamic] DEBUG: Got existing rate data for sensor: Package id 0 - rate: 0.000000, last_value 61.000000, last_time 37050415170
[dynamic] DEBUG: abs rate of change of sensor Package id 0: 0.234462 (t0: 59.000000, t-1: 61.000000, dv: -2.000000, dt: 8.530172)
[dynamic] DEBUG: EWMA abs rate of change of sensor Package id 0: 0.046892
[dynamic] MESSAGE: New highest EWMA rate sensor: Package id 0 (rate 0.046892)

**Comment by alexmurray** [comment]
Thanks for reporting this issue but it is actually a Ubuntu specific regression in the appindicator extension - https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/2059818

**Comment by alexmurray** [comment]
The fix is already available in the noble-proposed pocket and should hopefully be released to noble-updates within the next few days.

**Comment by herb2k** [comment]
Got it from noble-proposed and it is indeed working, thank you!

**Comment by alexmurray** [comment]
FWIW it looks like this update finally got released https://lists.ubuntu.com/archives/noble-changes/2024-June/039077.html
